# Generated by Django 4.0.3 on 2022-05-12 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_tags_new_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='news.tags', verbose_name='Теги'),
        ),
    ]
