# Generated by Django 4.0.3 on 2022-05-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_new_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='keywords',
            field=models.CharField(default='', max_length=150, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='new',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='new',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Понравилось'),
        ),
    ]
